package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/cygwin64/tmp/openjdk-jdk8u-windows-x64-hotspot/workspace/build/src/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, June 3, 2019 9:12:52 PM UTC
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
	 */
  public static final int value = (int)(20L);
}
